### ISSUE TITLE
首位不是符号, 是数字 会有显示Bug

### ISSUE THREAD

**Issue by HeathHsia** [MellongLau/AMAnimatedNumber#2]
![issues](https://user-images.githubusercontent.com/14340501/28665629-d96bade2-72f6-11e7-9ec1-379f8ee06cf8.png)

AMAnimatedNumber.m 文件 
setupLabels方法中 不去设置_maskView.frame即解决

看了大神的代码, 设计方式, 代码逻辑学到很多,   但是这种动画的实现方式不太赞同... 
关于数字类似这种动画我也会继续研究

**Comment by MellongLau** [comment]
已经修正，感谢指出这个大bug😅
