### ISSUE TITLE
提几个小问题

### ISSUE THREAD

**Issue by loveuqian** [MellongLau/AMAnimatedNumber#3]
* 小数数字的末位是 0 且 AMAnimateNumberDirectionUp 时，最后一个 0 没动画
* pod 上找不到 0.0.2 版本
* 字符串 "."（一个点） 的切割好像大了一点点
* 要是能支持自适应大小就更好了

不过都没事，已经用上了，感谢开源

**Comment by MellongLau** [comment]
数字是 0 没有动画的问题已经修复，v0.0.4，pod上已经可以搜到，当时可能忘了push上去，搜之前请先更新pod spec：
$ pod repo update
"."的问题不太明白你的意思。
自适应可能后续会支持。
因为这个issue时间较久了，先关了，如果有其他问题再提新的issue。
